name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check for calculadora.html
      run: |
        if [ -f calculadora.html ]; then
          echo "O arquivo calculadora.html existe."
        else
          echo "O arquivo calculadora.html não existe."
          exit 1
        fi

  run-js:
    needs: check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run JavaScript in calculadora.html
      run: |
        node -e 'console.log("Executando JavaScript dentro de calculadora.html")'

  print:
    needs: run-js
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Print Hello, World
      run: |
        echo 'Hello, World'

